### ISSUE TITLE
Rule: All genes should be connected to a taxon

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/release-utils#4]
All genes should have a direct edge to a taxon via RO:0002162 (in_taxon)

Query: 
```MATCH (gene:gene) WHERE NOT (gene)-[:RO:0002162]->() AND (gene:cliqueLeader) RETURN COUNT(DISTINCT(gene))```

As of this ticket 351,663 genes are missing an in_taxon edge

**Comment by TomConlin** [comment]
there is the question;  
can all the clique leaders be tagged w/taxon and if so is that not  sufficent?

**Comment by kshefchek** [comment]
I think all genes should be tagged with a taxon, this ticket is just for tracking the counts across releases (I may be misunderstanding your question)

**Comment by TomConlin** [comment]
given
- genes may have multiple representations.
- those representations are gathered under the selected clique leader.
- If any representation has a  taxon, then the clique leader has a taxon.

Every gene __representation__ having a taxon mapping is a more stringent requirement  than every gene clique leader having a taxon mapping.

**Comment by kshefchek** [comment]
agreed, this is covered in the WHERE clause: ```WHERE NOT (gene)-[:RO:0002162]->() AND (gene:cliqueLeader)```

Non-clique leaders in scigraph have 0 incoming or outgoing edges except for sameAs and equivalentClass

**Comment by TomConlin** [comment]
+1
